version: "3"
services:
  nginx:
    image: nginx:1.16
    ports: 
      - 80:80
    volumes:
      - "./app:/var/www/html/"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - php

  php:
    build:
      context: ./php
    ports:
      - 9000:9000
    volumes: 
      - "./app:/var/www/html/"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASS=root
      - MYSQL_DB_NAME=webdocker
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - "db_data:/var/lib/mysql"
      - "./mysql/initial_data:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_ROOT_PASSWORD=root

volumes:
  db_data: