version: "3"
services:
  nginx:
    image: nginx:1.16.1
    ports: 
      - 80:80
    volumes:
      - "./app:/var/www/html/"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - php
  php:
    image: php:7.2-fpm
    ports:
      - 9000:9000
    volumes: 
      - "./app:/var/www/html/"